#!/usr/bin/env bash
set -euo pipefail

APP_ROOT="${APP_ROOT:-/opt/vyapar-genie}"
OUTPUT_FILE="${STAGING_ENV_FILE:-$APP_ROOT/.env.staging}"

required_vars=(
  APP_SITE
  NEXT_PUBLIC_API_BASE_URL
  WEB_BASE_URL
  API_CORS_ORIGIN
  COOKIE_SECURE
  COOKIE_SAMESITE
  TRUST_PROXY
  TRUST_PROXY_HOPS
  POSTGRES_DB
  POSTGRES_USER
  POSTGRES_PASSWORD
  DATABASE_URL
  REDIS_HOST
  REDIS_PORT
  JWT_ACCESS_SECRET
  JWT_REFRESH_SECRET
  JWT_ACCESS_TTL_SECONDS
  JWT_REFRESH_TTL_SECONDS
  FILE_SIGNING_SECRET
  FILE_STORAGE_DRIVER
  FILE_STORAGE_ROOT
)

for var_name in "${required_vars[@]}"; do
  if [[ -z "${!var_name:-}" ]]; then
    echo "Missing required environment variable: ${var_name}" >&2
    exit 1
  fi
done

mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" <<EOF
APP_SITE=${APP_SITE}
NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
WEB_BASE_URL=${WEB_BASE_URL}
API_CORS_ORIGIN=${API_CORS_ORIGIN}
COOKIE_SECURE=${COOKIE_SECURE}
COOKIE_SAMESITE=${COOKIE_SAMESITE}
COOKIE_DOMAIN=${COOKIE_DOMAIN:-}
TRUST_PROXY=${TRUST_PROXY}
TRUST_PROXY_HOPS=${TRUST_PROXY_HOPS}

POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=${DATABASE_URL}

REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}

JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_ACCESS_TTL_SECONDS=${JWT_ACCESS_TTL_SECONDS}
JWT_REFRESH_TTL_SECONDS=${JWT_REFRESH_TTL_SECONDS}
FILE_SIGNING_SECRET=${FILE_SIGNING_SECRET}

FILE_STORAGE_DRIVER=${FILE_STORAGE_DRIVER}
FILE_STORAGE_ROOT=${FILE_STORAGE_ROOT}
FILE_STORAGE_BUCKET=${FILE_STORAGE_BUCKET:-}
FILE_STORAGE_REGION=${FILE_STORAGE_REGION:-}
FILE_STORAGE_ENDPOINT=${FILE_STORAGE_ENDPOINT:-}
FILE_STORAGE_ACCESS_KEY_ID=${FILE_STORAGE_ACCESS_KEY_ID:-}
FILE_STORAGE_SECRET_ACCESS_KEY=${FILE_STORAGE_SECRET_ACCESS_KEY:-}

BILLING_STRIPE_SECRET_KEY=${BILLING_STRIPE_SECRET_KEY:-}
BILLING_STRIPE_WEBHOOK_SECRET=${BILLING_STRIPE_WEBHOOK_SECRET:-}
BILLING_RAZORPAY_KEY_ID=${BILLING_RAZORPAY_KEY_ID:-}
BILLING_RAZORPAY_KEY_SECRET=${BILLING_RAZORPAY_KEY_SECRET:-}
BILLING_RAZORPAY_WEBHOOK_SECRET=${BILLING_RAZORPAY_WEBHOOK_SECRET:-}

NOTIFICATIONS_EMAIL_WEBHOOK_URL=${NOTIFICATIONS_EMAIL_WEBHOOK_URL:-}
NOTIFICATIONS_SMS_WEBHOOK_URL=${NOTIFICATIONS_SMS_WEBHOOK_URL:-}
NOTIFICATIONS_WHATSAPP_WEBHOOK_URL=${NOTIFICATIONS_WHATSAPP_WEBHOOK_URL:-}
EOF

echo "Wrote staging env file to $OUTPUT_FILE"
